---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: windows-2012r2
    transport:
        name: winrm


suites:
  - name: default
    run_list:
      - recipe[wireshark::default]
    attributes:
